### ISSUE TITLE
Add menu option to create a job

### ISSUE THREAD

**Issue by NabaSadiaSiddiqui** [maxgala/aspire#15]
Add a menu option under `Jobs` to create a job. Currently, its only available by sliding open the drawer from left.

- [ ] Update empty card button with a button to create a job
- [ ] in the job board add button to post a job

Suggestion by Aazar

**Comment by ahmedhamodi** [comment]
Completed in https://github.com/maxgala/aspire-frontend/pull/298

**Comment by ahmedhamodi** [comment]
PR addressing this got merged.
