### ISSUE TITLE
Word count in `job description` does not update

### ISSUE THREAD

**Issue by NabaSadiaSiddiqui** [maxgala/aspire#16]
Reporter: Aazar

Feedback: I was cutting and pasting Job descriptions.  I pasted more than 2000 characters but didn't know that.  It said 2000/2000 characters and wouldn't let me post.  As I deleted words, it didn't change character count

And then when I tried to delete and enter, the character count remained.  It wasn't until I totally exited that area and pressed refresh that it reset.  

Basically it gets all wonky if I paste more than 2,000 characters and doesn't all ow me to easily correct my mistake without fully restarting over again

**Comment by ahmedhamodi** [comment]
Resolved.
